---
- name: check if sources.list exists
  stat:
    path: /etc/apt/sources.list
  register: ubuntu_repo_result

- name: disable ubuntu main repos
  block:
    - name: create backup of sources.list
      copy: remote_src=True src=/etc/apt/sources.list dest=/etc/apt/sources.list.bak

    - name: remove sources.list
      file: path=/etc/apt/sources.list state=absent

  when: ubuntu_repo_result.stat.exists == True

- name: check if 45drives.sources exists
  stat:
    path: /etc/apt/sources.list.d/45drives.sources
  register: ffd_repo_result

- name: disable 45drives repo
  block:
    - name: create backup of 45drives.sources
      copy: remote_src=True src=/etc/apt/sources.list.d/45drives.sources dest=/etc/apt/sources.list.d/45drives.sources.bak

    - name: remove 45drives.sources
      file: path=/etc/apt/sources.list.d/45drives.sources state=absent
  when: ffd_repo_result.stat.exists == True

- name: place offline repo file on each node
  template:
    src: "ubuntu-offline.list.j2"
    dest: "/etc/apt/sources.list.d/ubuntu-offline.list"
    owner: root
    group: root
    mode: 0644

- name: import apt keys for ceph, nfs-ganeha and 45drives
  apt_key:
    url: http://{{ offline_repo_server_ip }}/keys/{{ item }}.asc
    state: present
  loop:
    - 45drives
    - ceph
    - nfs-ganesha
    - docker-ce

- name: update apt cache
  apt:
    update_cache: yes
