---
- name: red hat based systems - repo handling
  when:
    - ceph_origin == 'repository'
    - ceph_nfs_server == 'ganesha'
    - not offline_install 
  block:
    - name: red hat based systems - stable repo related tasks
      when:
        - nfs_ganesha_stable | bool
        - ceph_repository == 'community' or ceph_repository == 'custom'
      block:
        - name: add nfs-ganesha stable repository
          yum_repository:
            name: nfs_ganesha_stable
            description: nfs-ganesha stable repo
            gpgcheck: yes
            state: present
            gpgkey: "{{ ceph_stable_key }}"
            baseurl: "{{ ceph_mirror }}/nfs-ganesha/rpm-{{ nfs_ganesha_stable_branch }}/octopus/el$releasever/$basearch"
            file: nfs_ganesha_stable

        - name: add nfs-ganesha stable noarch repository
          yum_repository:
            name: nfs_ganesha_stable_noarch
            description: nfs-ganesha stable noarch repo
            gpgcheck: yes
            state: present
            gpgkey: "{{ ceph_stable_key }}"
            baseurl: "{{ ceph_mirror }}/nfs-ganesha/rpm-{{ nfs_ganesha_stable_branch }}/octopus/el$releasever/noarch"
            file: nfs_ganesha_stable

    - name: red hat based systems - dev repo related tasks
      block:
        - name: add nfs-ganesha dev repo
          get_url:
            url: "https://shaman.ceph.com/api/repos/nfs-ganesha/next/latest/{{ ansible_facts['distribution'] | lower }}/{{ ansible_facts['distribution_major_version'] }}/flavors/{{ nfs_ganesha_flavor }}/repo"
            dest: /etc/yum.repos.d/nfs-ganesha-dev.repo
            force: true
      when:
        - nfs_ganesha_dev | bool
        - ceph_repository == 'dev'  

- name: red hat based systems - install nfs-ganesha packages
  when: ceph_nfs_server == 'ganesha'
  block:
    - name: install nfs cephfs gateway
      package:
        name: ['nfs-ganesha-ceph', 'nfs-ganesha-rados-grace', 'nfs-ganesha-rados-urls']
        state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      when: nfs_file_gw

    - name: install redhat nfs-ganesha-rgw and ceph-radosgw packages
      package:
        name: ['nfs-ganesha-rgw', 'nfs-ganesha-rados-grace', 'nfs-ganesha-rados-urls', 'ceph-radosgw']
        state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      when: nfs_obj_gw | bool

- name: red hat based systems - install nfs-utils
  when: ceph_nfs_server == 'kernel'
  block:
    - name: install nfs cephfs gateway
      package:
        name: nfs-utils
        state: "latest"
      register: result
      until: result is succeeded
      when: nfs_file_gw

- name: red hat based systems - install pacemaker/corosync/pcs
  when: ceph_nfs_rados_backend_driver == "rados_ng"
  block:
    - name: Enable HighAvailablity Repo on RHEL8/Rocky
      shell: dnf config-manager --set-enabled ha
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'
        - not offline_install

    - name: install pacemaker
      package:
        name: ['pacemaker', 'corosync', 'pcs']
        state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      when:
        - groups['nfss'] | length > 1

