---
- name: Enable and start PCS daemon
  service:
    name: pcsd
    enabled: true
    state: started

- name: Enable corosync/pacemaker daemon
  service:
    name: "{{ item }}"
    enabled: true
    state: stopped
  loop:
    - corosync
    - pacemaker

- name: Generate a password for the user {{ pcmk_user }}
  set_fact:
    pcmk_password: "{{ ansible_machine_id | to_uuid }}"
  run_once: true
  when: pcmk_password is not defined

- name: Set user {{ pcmk_user }} password
  user:
    name: "{{ pcmk_user }}"
    password: "{{ pcmk_password | password_hash('sha512') }}"

- name: Authenticate all nodes
  command: pcs cluster auth {{ ansible_play_batch | join(' ') }} -u "{{ pcmk_user }}" -p "{{ pcmk_password | quote }}"
  run_once: true
  args:
    creates: /var/lib/pcsd/tokens

- name: Setup message bus
  run_once: true
  command: pcs cluster setup --name {{ pcmk_cluster_name | quote }} {{  ansible_play_batch | join(' ') }}
  args:
    creates: /etc/corosync/corosync.conf

- name: Start the cluster
  command: pcs cluster start --all
  run_once: true

- name: Enable the cluster to start at boot time
  command: pcs cluster enable --all
  run_once: true

- name: Disable STONITH
  command: pcs property set stonith-enabled=false
  run_once: true

- name: Check for nfs_ganesha resource
  shell: "pcs resource show nfs_server"
  failed_when: false
  run_once: true
  register: nfs_resource_check

- name: Create NFS-Ganesha service resource
  command: pcs resource create nfs_server systemd:nfs-ganesha op monitor interval=10s
  run_once: true
  when: nfs_resource_check.rc == 1  

- name: Check for nfs_ip resource
  shell: "pcs resource show nfs_ip"
  failed_when: false
  run_once: true
  register: ip_resource_check

- name: Create Floating IP for NFS service
  command: pcs resource create nfs_ip ocf:heartbeat:IPaddr2 ip={{ ceph_nfs_floating_ip_address }} cidr_netmask={{ ceph_nfs_floating_ip_cidr }} op monitor interval=10s
  run_once: true
  when: ip_resource_check.rc == 1

- name: Check for resource constraint
  shell: "pcs constraint | grep 'nfs_server with nfs_ip'"
  failed_when: false
  run_once: true
  register: resource_constraint_check

- name: Set constraint on cluster resources
  command: pcs constraint colocation add nfs_server with nfs_ip INFINITY
  run_once: true
  when: resource_constraint_check.rc == 1
