---
galaxy_info:
  company: 45Drives
  author: Brett Kelly
  description: Handles 45drives ceph 45drives
  license: Apache
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
dependencies: []
