---
- name: Remove unneeded pkgs in ubuntu
  block:
    - name: Remove packages
      apt:
        name: "{{ ubuntu_cleanup_pkgs }}"
        state: absent
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

