- name: Remove unneeded pkgs in centos
  block:
    - name: Remove packages
      yum:
        name: "{{ centos_cleanup_pkgs }}"
        state: absent
      register: result
      until: result is succeeded
